// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106103543_aggiontomorefeautures")]
    partial class aggiontomorefeautures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FiscalCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PEC")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Referent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SDICode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("VATNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreationDate")
                        .HasDatabaseName("IX_ApplicationUser_CreationDate");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BackEnd.Entities.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("EventDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EventEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventLocation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EventStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Postponed")
                        .HasColumnType("boolean");

                    b.Property<int?>("RealEstatePropertyId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventStartDate")
                        .HasDatabaseName("IX_Calendar_EventStartDate");

                    b.HasIndex("RealEstatePropertyId");

                    b.HasIndex("RequestId");

                    b.HasIndex("EventStartDate", "EventEndDate")
                        .HasDatabaseName("IX_Calendar_StartDate_EndDate");

                    b.HasIndex("UserId", "EventStartDate")
                        .HasDatabaseName("IX_Calendar_UserId_StartDate");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcquisitionDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Builder")
                        .HasColumnType("boolean");

                    b.Property<bool>("Buyer")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("GoldCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OngoingAssignment")
                        .HasColumnType("boolean");

                    b.Property<bool>("Other")
                        .HasColumnType("boolean");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<bool>("Seller")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Customer_Email");

                    b.HasIndex("UserId", "CreationDate")
                        .HasDatabaseName("IX_Customer_UserId_CreationDate");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BackEnd.Entities.CustomerNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.Documentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("Documentation");
                });

            modelBuilder.Entity("BackEnd.Entities.DocumentsTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BoilerMaintenanceLog")
                        .HasColumnType("boolean");

                    b.Property<int?>("BoilerMaintenanceLogDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("BuildingCadastralComplianceReport")
                        .HasColumnType("boolean");

                    b.Property<int?>("BuildingCadastralComplianceReportDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("CadastralMapExtract")
                        .HasColumnType("boolean");

                    b.Property<int?>("CadastralMapExtractDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("CadastralSurveyAndFloorPlan")
                        .HasColumnType("boolean");

                    b.Property<int?>("CadastralSurveyAndFloorPlanDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("ChamberOfCommerceBusinessRegistrySearch")
                        .HasColumnType("boolean");

                    b.Property<int?>("ChamberOfCommerceBusinessRegistrySearchDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("CommissionAgreement")
                        .HasColumnType("boolean");

                    b.Property<int?>("CommissionAgreementDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("Condominium")
                        .HasColumnType("boolean");

                    b.Property<bool>("CondominiumBylaws")
                        .HasColumnType("boolean");

                    b.Property<int?>("CondominiumBylawsDocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CondominiumDocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeedOfOrigin")
                        .HasColumnType("boolean");

                    b.Property<int?>("DeedOfOriginDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("DeedOfSale")
                        .HasColumnType("boolean");

                    b.Property<int?>("DeedOfSaleDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("ElectricalElectronicSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("ElectricalElectronicSystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("EnergyPerformanceCertificate")
                        .HasColumnType("boolean");

                    b.Property<int?>("EnergyPerformanceCertificateDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("FireSafetySystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("FireSafetySystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("FloorPlanWithSubsidiaryUnits")
                        .HasColumnType("boolean");

                    b.Property<int?>("FloorPlanWithSubsidiaryUnitsDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("GasSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("GasSystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("HabitabilityCertificate")
                        .HasColumnType("boolean");

                    b.Property<int?>("HabitabilityCertificateDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("HeatingAirConditioningSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeatingAirConditioningSystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IdentificationDocument")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdentificationDocumentDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LandRegistry")
                        .HasColumnType("boolean");

                    b.Property<int?>("LandRegistryDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LastMortgagePaymentReceipt")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastMortgagePaymentReceiptDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LastTwoCondominiumMeetingMinutes")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastTwoCondominiumMeetingMinutesDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LatestFinancialStatementAndBudget")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatestFinancialStatementAndBudgetDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LeaseAgreement")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeaseAgreementDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("LiftingSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("LiftingSystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("MarriageCertificateSummary")
                        .HasColumnType("boolean");

                    b.Property<int?>("MarriageCertificateSummaryDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("MillesimalTables")
                        .HasColumnType("boolean");

                    b.Property<int?>("MillesimalTablesDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("MiscellaneousDocuments")
                        .HasColumnType("boolean");

                    b.Property<int?>("MiscellaneousDocumentsDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("MortgageDeed")
                        .HasColumnType("boolean");

                    b.Property<int?>("MortgageDeedDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("MortgageLienRegistrySearch")
                        .HasColumnType("boolean");

                    b.Property<int?>("MortgageLienRegistrySearchDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("PlumbingSanitarySystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlumbingSanitarySystemDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("PowerOfAttorney")
                        .HasColumnType("boolean");

                    b.Property<int?>("PowerOfAttorneyDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("PreliminarySaleAgreement")
                        .HasColumnType("boolean");

                    b.Property<int?>("PreliminarySaleAgreementDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("PurchaseOffer")
                        .HasColumnType("boolean");

                    b.Property<int?>("PurchaseOfferDocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("RealEstatePropertyDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("SignedStatementFromAdministrator")
                        .HasColumnType("boolean");

                    b.Property<int?>("SignedStatementFromAdministratorDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("StructuralIntegrityCertificate")
                        .HasColumnType("boolean");

                    b.Property<int?>("StructuralIntegrityCertificateDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("SystemsComplianceDeclaration")
                        .HasColumnType("boolean");

                    b.Property<int?>("SystemsComplianceDeclarationDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxCodeOrHealthCard")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaxCodeOrHealthCardDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxDeductionDocumentation")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaxDeductionDocumentationDocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UrbanPlanningComplianceCertificate")
                        .HasColumnType("boolean");

                    b.Property<int?>("UrbanPlanningComplianceCertificateDocumentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DocumentsTabs");
                });

            modelBuilder.Entity("BackEnd.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StripeChargeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StripePaymentIntentId")
                        .HasDatabaseName("IX_Payment_StripePaymentIntentId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("AgreedCommission")
                        .HasColumnType("integer");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AssignmentEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Auction")
                        .HasColumnType("boolean");

                    b.Property<string>("Availability")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CommercialSurfaceate")
                        .HasColumnType("integer");

                    b.Property<int>("CommissionReversal")
                        .HasColumnType("integer");

                    b.Property<double>("CondominiumExpenses")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("Elevators")
                        .HasColumnType("integer");

                    b.Property<string>("EnergyClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Exposure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FlatRateCommission")
                        .HasColumnType("integer");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Furniture")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Heating")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("boolean");

                    b.Property<bool>("InHome")
                        .HasColumnType("boolean");

                    b.Property<int>("Kitchens")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MQGarden")
                        .HasColumnType("integer");

                    b.Property<string>("MoreDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MoreFeatures")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Negotiation")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherFeatures")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceReduced")
                        .HasColumnType("double precision");

                    b.Property<bool>("Sold")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateOfTheProperty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalBuildingfloors")
                        .HasColumnType("integer");

                    b.Property<string>("TypeOfAssignment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeOfProperty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Typology")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("WarehouseRooms")
                        .HasColumnType("integer");

                    b.Property<int>("YearOfConstruction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Archived")
                        .HasDatabaseName("IX_RealEstateProperty_Archived");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_RealEstateProperty_Category");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Sold")
                        .HasDatabaseName("IX_RealEstateProperty_Sold");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RealEstateProperty_Status");

                    b.HasIndex("UserId", "CreationDate")
                        .HasDatabaseName("IX_RealEstateProperty_AgentId_CreationDate");

                    b.HasIndex("City", "Category", "Status")
                        .HasDatabaseName("IX_RealEstateProperty_City_Category_Status");

                    b.ToTable("RealEstateProperties");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RealEstatePropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstatePropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("RealEstatePropertyNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RealEstatePropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstatePropertyId");

                    b.ToTable("RealEstatePropertyPhotos");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("GardenFrom")
                        .HasColumnType("integer");

                    b.Property<int>("GardenTo")
                        .HasColumnType("integer");

                    b.Property<string>("Heating")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MQFrom")
                        .HasColumnType("integer");

                    b.Property<int>("MQTo")
                        .HasColumnType("integer");

                    b.Property<bool>("MortgageAdviceRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<double>("PriceFrom")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceTo")
                        .HasColumnType("double precision");

                    b.Property<string>("PropertyState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomsNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Archived")
                        .HasDatabaseName("IX_Request_Archived");

                    b.HasIndex("Closed")
                        .HasDatabaseName("IX_Request_Closed");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.HasIndex("Province", "City")
                        .HasDatabaseName("IX_Request_Province_City");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("BackEnd.Entities.RequestNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_StripeWebhookEvent_EventId");

                    b.ToTable("StripeWebhookEvents");
                });

            modelBuilder.Entity("BackEnd.Entities.SubscriptionFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FeatureValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionFeatures");
                });

            modelBuilder.Entity("BackEnd.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("IX_SubscriptionPlan_Active");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("BackEnd.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastPaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastPaymentId");

                    b.HasIndex("StripeSubscriptionId")
                        .HasDatabaseName("IX_UserSubscription_StripeSubscriptionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_UserSubscription_UserId_Status");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BackEnd.Entities.Calendar", b =>
                {
                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany()
                        .HasForeignKey("RealEstatePropertyId");

                    b.HasOne("BackEnd.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RealEstateProperty");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.CustomerNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.Customer", null)
                        .WithMany("CustomerNotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.Payment", b =>
                {
                    b.HasOne("BackEnd.Entities.UserSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany("RealEstateProperties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany("RealEstateProperties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany("RealEstatePropertyNotes")
                        .HasForeignKey("RealEstatePropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateProperty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyPhoto", b =>
                {
                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany("Photos")
                        .HasForeignKey("RealEstatePropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateProperty");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.RequestNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.Request", null)
                        .WithMany("RequestNotes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.SubscriptionFeature", b =>
                {
                    b.HasOne("BackEnd.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Features")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("BackEnd.Entities.UserSubscription", b =>
                {
                    b.HasOne("BackEnd.Entities.Payment", "LastPayment")
                        .WithMany()
                        .HasForeignKey("LastPaymentId");

                    b.HasOne("BackEnd.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastPayment");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("RealEstateProperties");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.Navigation("CustomerNotes");

                    b.Navigation("RealEstateProperties");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("RealEstatePropertyNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.Navigation("RequestNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
